[package]
name = "Rainier"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
rand = "0.9.2"

[profile.dev]
overflow-checks = false
